# 1️⃣ PROJECT INTRODUCTION

<h1 style="color:#1F618D; text-align:center;">🚇 Tunnel Boring Machine (TBM) Penetration Rate Optimization</h1>

<h3 style="text-align:center;">AI Engineer | Industrial Machine Learning Project</h3>

<hr>

<h2 style="color:#117A65;">📌 Project Overview</h2>

This project focuses on predicting and optimizing the <b>Penetration Rate (PR)</b> of a Tunnel Boring Machine (TBM)
using sensor-based operational and geological parameters.

The dataset contains noisy industrial sensor readings.
Therefore, preprocessing and weak supervision techniques are applied.

<h2 style="color:#117A65;">🎯 Business Objective</h2>

<ul>
<li>Predict TBM Penetration Rate (PR)</li>
<li>Handle noisy industrial sensor data</li>
<li>Compare ML models (WEKA vs Python)</li>
<li>Interpret confusion matrix & performance metrics</li>
</ul>

# 1. Data Understanding📊

<h1 style="color:#0B5394; border-bottom:3px solid #0B5394; padding-bottom:8px;">
1. Data Understanding
</h1>

<p style="font-size:15px; line-height:1.6;">
Before building any machine learning model, it is critical to understand the structure,
dimensions, data types, and quality of the dataset.
This step ensures that modeling decisions are based on proper data awareness.
</p>

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_excel("TBM data Exam.xlsx")
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Sr,Stroke No.,Date,Advance Time,Excavation per Stroke,Boring Energy,RPM,Torque,Thrust Force,Speed,Gripper Pressure,Total Revolution,Front Shield Pressure LHS,Front Shield Pressure rHS,Q-Value,Q-Value based,Penetration
1,NaN,NaN,NaN,min,(m),(N/mm2),NaN,(KN-m),(KN),(mm/min),(Bar),NaN,(Bar),(Bar),NJC,Boring Energy,(mm/rpm)
2,1,3812,2016-01-23 00:00:00,16,1.612,1.3,2.3,500,3600,101,253,37,80,58,4,5,44.5
3,2,3813,2016-01-23 00:00:00,78,1.559,9.9,2.3,800,3224,20,242,179,60,62,4,4,8.6
4,3,3814,2016-01-23 00:00:00,43,0.901,9.3,2,900,2895,21,245,86,69,69,4,5,10.5

In [2]:
df.shape

(1474, 17)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1474 entries, 0 to 1473
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1473 non-null   object
 1   Unnamed: 1   1473 non-null   object
 2   Unnamed: 2   1473 non-null   object
 3   Unnamed: 3   1474 non-null   object
 4   Unnamed: 4   1474 non-null   object
 5   Unnamed: 5   1474 non-null   object
 6   Unnamed: 6   1473 non-null   object
 7   Unnamed: 7   1474 non-null   object
 8   Unnamed: 8   1474 non-null   object
 9   Unnamed: 9   1474 non-null   object
 10  Unnamed: 10  1474 non-null   object
 11  Unnamed: 11  1473 non-null   object
 12  Unnamed: 12  1474 non-null   object
 13  Unnamed: 13  1474 non-null   object
 14  Unnamed: 14  1474 non-null   object
 15  Unnamed: 15  1474 non-null   object
 16  Unnamed: 16  1474 non-null   object
dtypes: object(17)
memory usage: 195.9+ KB

In [4]:
df.describe()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
count,1473,1473,1473,1474,1474.00,1474.0,1473.0,1474,1474,1474,1474,1473,1474,1474,1474,1474,1474.0
unique,213,1240,220,73,479.00,259.0,35.0,38,1205,46,65,147,70,80,4,6,87.0
top,1,3995,2016-11-05 00:00:00,26,1.23,11.4,3.8,1200,3861,44,189,109,31,32,4,4,12.9
freq,11,2,18,153,52.00,30.0,147.0,186,4,124,233,56,67,66,1075,739,55.0

<h3 style="color:#1C4587;">Observations:</h3>

<ul style="font-size:15px; line-height:1.6;">
<li>The dataset contains TBM operational parameters collected from industrial sensors.</li>
<li>Column names appear misaligned and include structural issues.</li>
<li>Several columns are stored as object data types instead of numeric.</li>
<li>Initial rows seem to contain duplicated header information.</li>
</ul>

<p style="font-size:15px;">
Conclusion: Structural cleaning is required before analysis.
</p>

# 🧹 STEP 2 — DATA CLEANING

<h1 style="color:#38761D; border-bottom:3px solid #38761D; padding-bottom:8px;">
2. Data Cleaning and Structural Correction
</h1>

<p style="font-size:15px;">
Industrial datasets often contain formatting inconsistencies,
missing values, and incorrect data types.
This section corrects structural issues to prepare the dataset for analysis.
</p>

### 🔷 Code: Fix Column Headers

In [11]:


df.columns = df.iloc[0]     # First row becomes header
df = df[1:]                 # Remove first row
df.reset_index(drop=True, inplace=True)

df.head()

,3,3814,2016-01-23 00:00:00,43,0.901,9.3,2,900,2895,21,245,86,69,69,4,5,10.5
0,4,3815,2016-01-24 00:00:00,80,1.396,15.6,2,1300,2962,18,245,160,59,66,4,3,8.9
1,5,3816,2016-01-24 00:00:00,71,1.526,7.1,2.3,600,3709,21,456,163,75,78,4,5,9.4
2,6,3817,2016-01-25 00:00:00,37,0.909,11.4,2.4,1100,3866,25,322,89,74,58,4,4,10.3
3,1,3819,2016-05-02 00:00:00,58,1.406,6.3,2,700,3229,24,243,116,79,74,4,5,12.2
4,2,3820,2016-06-02 00:00:00,60,1.444,11.9,2.2,1200,3054,24,245,132,75,75,4,4,11

In [12]:
# remove unwanted columns
df = df.dropna(axis=1, how='all')

# Remove columns containing "Unnamed"
df = df.loc[:, ~df.columns.astype(str).str.contains('Unnamed')]

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1469 entries, 0 to 1468
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   3                    1469 non-null   object
 1   3814                 1469 non-null   object
 2   2016-01-23 00:00:00  1469 non-null   object
 3   43                   1469 non-null   object
 4   0.901                1469 non-null   object
 5   9.3                  1469 non-null   object
 6   2                    1469 non-null   object
 7   900                  1469 non-null   object
 8   2895                 1469 non-null   object
 9   21                   1469 non-null   object
 10  245                  1469 non-null   object
 11  86                   1469 non-null   object
 12  69                   1469 non-null   object
 13  69                   1469 non-null   object
 14  4                    1469 non-null   object
 15  5                    1469 non-null   object
 16  10.5                 1469 non-null   object
dtypes: object(17)
memory usage: 195.2+ KB

In [22]:
df.columns

Index([                  3,                3814, 2016-01-23 00:00:00,
                        43,               0.901,                 9.3,
                         2,                 900,                2895,
                        21,                 245,                  86,
                        69,                  69,                   4,
                         5,                10.5],
      dtype='object', name=0)

In [23]:
df.columns.duplicated()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False])

In [24]:
df.columns[df.columns.duplicated()]

Index([69], dtype='object', name=0)

In [25]:
df = df.apply(pd.to_numeric, errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1469 entries, 0 to 1468
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   3                    1469 non-null   int64
 1   3814                 1469 non-null   int64
 2   2016-01-23 00:00:00  0 non-null      float64
 3   43                   1469 non-null   int64
 4   0.901                1469 non-null   float64
 5   9.3                  1469 non-null   float64
 6   2                    1469 non-null   float64
 7   900                  1469 non-null   int64
 8   2895                 1469 non-null   int64
 9   21                   1469 non-null   int64
 10  245                  1469 non-null   int64
 11  86                   1469 non-null   int64
 12  69                   1469 non-null   int64
 13  69                   1469 non-null   int64
 14  4                    1469 non-null   int64
 15  5                    1469 non-null   int64
 16  10.5                 1469 non-null   float64
dtypes: float64(5), int64(12)
memory usage: 195.2 KB

In [26]:
df.columns.duplicated()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False])

In [ ]:
# Make column names unique
# import the pandas.io.parsers module

df.columns = pd.io.parsers.ParserBase({'names': df.columns})._maybe_dedup_names(df.columns)

df = df.apply(pd.to_numeric, errors='coerce')
df.info()

AttributeError: module 'pandas.io.parsers' has no attribute 'ParserBase'

### 🔷 Code: Convert to Numeric

In [27]:
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df.info()

TypeError: arg must be a list, tuple, 1-d array, or Series

### 🔷 Code: Handle Missing Values

In [7]:
# handle the missing values
df.isna().sum()

0
1                      0
3812                   0
2016-01-23 00:00:00    0
16                     0
1.612                  0
1.3                    0
2.3                    0
500                    0
3600                   0
101                    0
253                    0
37                     0
80                     0
58                     0
4                      0
5                      0
44.5                   0
dtype: int64

In [8]:
df = df.fillna(df.mean(numeric_only=True))
df.head()

,1,3812,2016-01-23 00:00:00,16,1.612,1.3,2.3,500,3600,101,253,37,80,58,4,5,44.5
0,3,3814,2016-01-23 00:00:00,43,0.901,9.3,2,900,2895,21,245,86,69,69,4,5,10.5
1,4,3815,2016-01-24 00:00:00,80,1.396,15.6,2,1300,2962,18,245,160,59,66,4,3,8.9
2,5,3816,2016-01-24 00:00:00,71,1.526,7.1,2.3,600,3709,21,456,163,75,78,4,5,9.4
3,6,3817,2016-01-25 00:00:00,37,0.909,11.4,2.4,1100,3866,25,322,89,74,58,4,4,10.3
4,1,3819,2016-05-02 00:00:00,58,1.406,6.3,2,700,3229,24,243,116,79,74,4,5,12.2

<h3 style="color:#274E13;">Observations:</h3>

<ul style="font-size:15px;">
<li>Header rows have been successfully corrected.</li>
<li>All operational parameters are now in numeric format.</li>
<li>Missing values were handled using mean imputation.</li>
</ul>

<p>
The dataset is now structurally consistent and ready for exploratory analysis.
</p>

# 📊 STEP 3 — EXPLORATORY DATA ANALYSIS (EDA)

<h1 style="color:#990000; border-bottom:3px solid #990000; padding-bottom:8px;">
3. Exploratory Data Analysis
</h1>

<p style="font-size:15px;">
EDA helps uncover relationships between TBM operational variables
and penetration performance.
Understanding correlations is essential before model training.
</p>

### 🔷 Code: Correlation Heatmap

In [10]:


# Select only numeric columns
numeric_df = df.select_dtypes(include=['number'])

plt.figure(figsize=(12,8))
sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

ValueError: zero-size array to reduction operation fmin which has no identity