# data inconsistencies

In [111]:
import pandas as pd

In [ ]:
# Now making a dataframe with some inconsistencies in the dates and some missing values in the 'Value' column
data = {
    'date': ['2021-12-01', '01-12-2022', '2022/12/01', '12-01-2021'],
    'country': ['USA', 'U.S.A.', 'America', 'United States'],
    'name': ['John Doe', 'John Doe', 'Jane Doe', 'Jane Doe'],
    'sales_2020': [100, 200, None, 200],
    'sales_2021': [None, 150, 300, 150]
}

In [113]:
# make it pandas dataframe
df = pd.DataFrame(data)

In [114]:
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01            USA  John Doe       100.0         NaN
1  01-12-2022         U.S.A.  John Doe       200.0       150.0
2  2022/12/01        America  Jane Doe         NaN       300.0
3  12-01-2021  United States  Jane Doe       200.0       150.0

In [115]:
# standarizing the data format
df['date'] = pd.to_datetime(df['date'], errors='coerce')
df['date'] = df['date'].dt.strftime('%Y-%m-%d')

In [116]:
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01            USA  John Doe       100.0         NaN
1         NaN         U.S.A.  John Doe       200.0       150.0
2         NaN        America  Jane Doe         NaN       300.0
3         NaN  United States  Jane Doe       200.0       150.0

In [117]:
# fill the values using ffill 


df['date'] = df['date'].fillna(method='ffill')

C:\Users\Muhammad Asim\AppData\Local\Temp\ipykernel_6888\3849541852.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['date'] = df['date'].fillna(method='ffill')

In [118]:
# we can also use the bfill method to fill the missing values
df['date'] = df['date'].fillna(method='bfill')

C:\Users\Muhammad Asim\AppData\Local\Temp\ipykernel_6888\1856032273.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['date'] = df['date'].fillna(method='bfill')

In [119]:
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01            USA  John Doe       100.0         NaN
1  2021-12-01         U.S.A.  John Doe       200.0       150.0
2  2021-12-01        America  Jane Doe         NaN       300.0
3  2021-12-01  United States  Jane Doe       200.0       150.0

In [120]:
# Now Harmonize the name of country
country_mapping = {
    'U.S.A.': 'United States',
    'America': 'United States',
    'USA': 'United States'
    
}

df['country'] = df['country'].map(country_mapping)

In [121]:
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01  United States  John Doe       100.0         NaN
1  2021-12-01  United States  John Doe       200.0       150.0
2  2021-12-01  United States  Jane Doe         NaN       300.0
3  2021-12-01            NaN  Jane Doe       200.0       150.0

In [122]:
# Now correct the typographical mistake 
# let's assume that the 'John Doe' to 'Jane Doe' 

df['name'] = df['name'].str.replace('John Doe', 'Jane Doe')
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01  United States  Jane Doe       100.0         NaN
1  2021-12-01  United States  Jane Doe       200.0       150.0
2  2021-12-01  United States  Jane Doe         NaN       300.0
3  2021-12-01            NaN  Jane Doe       200.0       150.0

In [123]:
# Now remove duplicates 

df = df.drop_duplicates(subset="name")
df.head()

         date        country      name  sales_2020  sales_2021
0  2021-12-01  United States  Jane Doe       100.0         NaN