# Outliers in Data

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.DataFrame({'age': [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 130]})
data.head()

   age
0   21
1   22
2   23
3   24
4   25

In [4]:
data

    age
0    21
1    22
2    23
3    24
4    25
5    26
6    27
7    28
8    29
9    30
10  130

In [5]:
# calculate the mean and standard deviation
mean = data['age'].mean()
std = data['age'].std()
# calculate the z-scores
data['Z-score'] = (data['age'] - mean) / std
data.head()

   age   Z-score
0   21 -0.442498
1   22 -0.410891
2   23 -0.379284
3   24 -0.347677
4   25 -0.316070

In [6]:
# Now print the data with outliers
print('Here is the data with outliers: \n', data)
print('____________________________________________')
# print the outliers
print(f"Here is the data based on z-score threshold, 3:\n {data[data['Z-score'] > 3]}")

Here is the data with outliers:
     age   Z-score
0    21 -0.442498
1    22 -0.410891
2    23 -0.379284
3    24 -0.347677
4    25 -0.316070
5    26 -0.284463
6    27 -0.252856
7    28 -0.221249
8    29 -0.189642
9    30 -0.158035
10  130  3.002663
____________________________________________
Here is the data based on z-score threshold, 3:
     age   Z-score
10  130  3.002663

In [7]:
# Remove the outliers
data = data[data['Z-score'] < 3]
print('Here is the data without outliers: \n', data)

Here is the data without outliers:
    age   Z-score
0   21 -0.442498
1   22 -0.410891
2   23 -0.379284
3   24 -0.347677
4   25 -0.316070
5   26 -0.284463
6   27 -0.252856
7   28 -0.221249
8   29 -0.189642
9   30 -0.158035

# Using IQR method

In [8]:
# import the scipy library
from scipy import stats
# now make new dataFrame
data2 = pd.DataFrame({'age': [2, 3, 4, 5, 6, 7, 8, 9, 10, 110]})
print('Here is the new data with outliers: \n', data2)
print('____________________________________________')
# now using quartiles to find the outliers
Q1 = data2['age'].quantile(0.25)
Q3 = data2['age'].quantile(0.75)
IQR = Q3 - Q1
print(IQR) 
# now find the outliers
outliers = data2[(data2['age'] < Q1 - 1.5 * IQR) | (data2['age'] > Q3 + 1.5 * IQR)]
print('Here are the outliers based on IQR method: \n', outliers)
print('____________________________________________')
# remove the outliers
data2 = data2[(data2['age'] >= Q1 - 1.5 * IQR) & (data2['age'] <= Q3 + 1.5 * IQR)]
print('Here is the data without outliers: \n', data2)

Here is the new data with outliers:
    age
0    2
1    3
2    4
3    5
4    6
5    7
6    8
7    9
8   10
9  110
____________________________________________
4.5
Here are the outliers based on IQR method:
    age
9  110
____________________________________________
Here is the data without outliers:
    age
0    2
1    3
2    4
3    5
4    6
5    7
6    8
7    9
8   10

# Now using K mean clustring and removing the outliers

In [13]:
# import library
from sklearn.cluster import KMeans
# create a new dataFrame
data = [[1, 2], [1, 4], [1, 0],
        [4, 2], [4, 4], [4, 0]]
# create a KMeans model
kmeans = KMeans(n_clusters=2, random_state=0).fit(data)
# predict clusters table
labels = kmeans.predict(data)
# indentify outliers based on clusters lebels
outliers = [data[i] for i, label in enumerate(labels) if label == 1]
# print the data and outliers
print('=================================================')
print('Here is the data: \n', data)
print('Here are the outliers based on KMeans clustering: \n', outliers)
print('=================================================')
# removing the outliers
data = [point for point in data if point not in outliers]
print('Here is the data without outliers: \n', data)
print('=================================================')

=================================================
Here is the data:
 [[1, 2], [1, 4], [1, 0], [4, 2], [4, 4], [4, 0]]
Here are the outliers based on KMeans clustering:
 [[1, 2], [1, 0]]
=================================================
Here is the data without outliers:
 [[1, 4], [4, 2], [4, 4], [4, 0]]
=================================================

c:\Users\Muhammad Asim\miniconda3\envs\ml_python\lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

# Merging Data

In [15]:
# import the library
import pandas as pd
# Create a new data set for merging
data1 = pd.DataFrame({'id': [1, 2, 3, 4, 5],
                      'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve']})
data2 = pd.DataFrame({'id': [1, 2, 3, 4, 5],
                      'age': [25, 30, 35, 40, 45]})
# print the both data sets
print('Here is the first data set: \n', data1)
print('Here is the second data set: \n', data2)
print('=================================================')
# merge the data 
merged_data = pd.merge(data1, data2, on='id', how='inner')
print('Here is the merged data: \n', merged_data)
print('=================================================')

Here is the first data set:
    id     name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David
4   5      Eve
Here is the second data set:
    id  age
0   1   25
1   2   30
2   3   35
3   4   40
4   5   45
=================================================
Here is the merged data:
    id     name  age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40
4   5      Eve   45
=================================================

In [17]:
# Now data concatenation
# create two data sets for concatenation
data1 = pd.DataFrame({'id': [1, 2, 3],
                      'name': ['Alice', 'Bob', 'Charlie']})
data2 = pd.DataFrame({'id': [4, 5, 6],
                      'name': ['David', 'Eve', 'Frank']})
# print the both data sets
print('Here is the first data set: \n', data1)
print('Here is the second data set: \n', data2) 
# concatenate the data
concatenated_data = pd.concat([data1, data2], ignore_index=True)
print('Here is the concatenated data: \n', concatenated_data)
print('=================================================')
# now using rows and columns concatenation
concatenated_data_rows = pd.concat([data1, data2], ignore_index=True)
concatenated_data_columns = pd.concat([data1, data2], axis=1)
print('Here is the concatenated data based on rows: \n', concatenated_data_rows)
print('Here is the concatenated data based on columns: \n', concatenated_data_columns)

Here is the first data set:
    id     name
0   1    Alice
1   2      Bob
2   3  Charlie
Here is the second data set:
    id   name
0   4  David
1   5    Eve
2   6  Frank
Here is the concatenated data:
    id     name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David
4   5      Eve
5   6    Frank
=================================================
Here is the concatenated data based on rows:
    id     name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David
4   5      Eve
5   6    Frank
Here is the concatenated data based on columns:
    id     name  id   name
0   1    Alice   4  David
1   2      Bob   5    Eve
2   3  Charlie   6  Frank